import 'package:flutter/material.dart';

class ColorSchemeData {
  ColorSchemeData({
    required this.brand,
    required this.primary1,
    required this.primary2,
    required this.secondary1,
    required this.secondary2,
    required this.tertiary0,
    required this.tertiary3,
    required this.tertiary5,
    required this.tertiary7,
    required this.tertiary10,
    required this.tertiary12,
    required this.tertiary15,
    required this.tile1,
    required this.tile2,
    required this.tile3,
    required this.tile5,
    required this.primaryButton1,
    required this.primaryButton2,
    required this.button1a,
    required this.button1b,
    required this.button2a,
    required this.button2b,
    required this.button2c,
    required this.button2d,
    required this.button3a,
    required this.button3b,
    required this.button5a,
    required this.button5b,
    required this.successPrimary1,
    required this.success1,
    required this.success2,
    required this.error,
    required this.shadow,
    required this.outLine1,
  });
  Color brand;
  Color primary1;
  Color primary2;
  Color secondary1;
  Color secondary2;
  Color tertiary0;
  Color tertiary3;
  Color tertiary5;
  Color tertiary7;
  Color tertiary10;
  Color tertiary12;
  Color tertiary15;
  Color tile1;
  Color tile2;
  Color tile3;
  Color tile5;
  Color primaryButton1;
  Color primaryButton2;
  Color button1a;
  Color button1b;
  Color button2a;
  Color button2b;
  Color button2c;
  Color button2d;
  Color button3a;
  Color button3b;
  Color button5a;
  Color button5b;
  Color successPrimary1;
  Color success1;
  Color success2;
  Color error;
  Color shadow;
  Color outLine1;
}
